# Create configmap before running the template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresapi-deploy
  labels:
    app: postgresapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgresapi
  template:
    metadata:
      labels:
        app: postgresapi
    spec:
      containers:
        - name: postgresapi
          image: nikxgupta/postgresapi:v2
          imagePullPolicy: Always
          env:
          - name: postgres_conn
            value: "host=postgres-server user=postgres password=demo@123 dbname=postgres sslmode=disable"
          - name: PG_EXPORTER_DISABLE_SETTINGS_METRICS
            value: "true"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-prom
  labels:
    app: postgres-prom
spec:
  selector:
    matchLabels:
      app: postgres-prom
  template:
    metadata:
      labels:
        app: postgres-prom
    spec:
      containers:
        - name: postgres-scraper
          image: quay.io/prometheuscommunity/postgres-exporter
          env:
          - name: DATA_SOURCE_NAME
            value: "host=postgres-server user=postgres password=demo@123 dbname=postgres sslmode=disable"
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: config-volume
          configMap:
            name: prom-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgresapi-svc
spec:
  selector:
    app: postgresapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 12112
      targetPort: 2112
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-prom-svc
spec:
  selector:
    app: postgres-prom
  type: NodePort
  ports:
    - protocol: TCP
      port: 19187
      targetPort: 9187
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - protocol: TCP
      port: 19090
      targetPort: 9090

  
