apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres-server
  namespace: default
spec:
   replicas: 3
   image: postgres:13.2
   database:
      size: 2Gi
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret
              key: superUserPassword
      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret
              key: replicationUserPassword

